language: node

services:
  docker

stages:
  - build & push

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build & push
      script:
        - docker build -t $DOCKER_USERNAME/udagram-api-user:v1 ./udagram-api-user
        - docker push $DOCKER_USERNAME/udagram-api-user:v1
        - docker build -t $DOCKER_USERNAME/udagram-api-feed:v1 ./udagram-api-feed
        - docker push $DOCKER_USERNAME/udagram-api-feed:v1
        - docker build -t $DOCKER_USERNAME/udagram-frontend:v6 ./udagram-frontend
        - docker push $DOCKER_USERNAME/udagram-frontend:v6
        - docker build -t $DOCKER_USERNAME/reverseproxy:v1 ./udagram-reverseproxy
        - docker push $DOCKER_USERNAME/reverseproxy:v1
