apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: qausim/reverseproxy:v1
        resources:
          requests:
            memory: "800Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
spec:
  selector:
    app: reverseproxy
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

